Operating on the Logical Qubit after it's been encoded into Shor's 9-Qubit Quantum Error Correcting Code

In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

#Sigma-X   sigmax()
#Sigma-Y   sigmay()
#Sigma-Z   sigmaz()
#Sigma plus   sigmap()
#Sigma minus   sigmam()
#identity   qeye(N)  (N=no. levels in hilbert space)

In [2]:
#Logical 0 state encoded onto 9 Qubits
ket0 = Qobj([[0],[1]])
print(ket0)

Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]


In [3]:
a=basis(3, 0) + basis(3, 1) + basis(3, 2)
b=basis(3, 0) + basis(3, 1) + basis(3, 2)
c=tensor(a,b)
print(a)
print(b)
print(c)
d=tensor(c,ket0)
print(d)

Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[1.]
 [1.]
 [1.]]
Quantum object: dims = [[3], [1]], shape = (3, 1), type = ket
Qobj data =
[[1.]
 [1.]
 [1.]]
Quantum object: dims = [[3, 3], [1, 1]], shape = (9, 1), type = ket
Qobj data =
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]
Quantum object: dims = [[3, 3, 2], [1, 1, 1]], shape = (18, 1), type = ket
Qobj data =
[[0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]]


In [8]:
spin = basis(2,1)
print(spin)
z=sigmaz()
print(z)
print(z * spin)


Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.]
 [1.]]
Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[ 0.]
 [-1.]]


In [5]:
#Logical NOT Gate
ID9x9Matrix = qeye(9)
X = sigmax()
LogicalNOT = tensor(ID9x9Matrix,X)
print(LogicalNOT)

Quantum object: dims = [[9, 2], [9, 2]], shape = (18, 18), type = oper, isherm = True
Qobj data =
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 

In [7]:
print(LogicalNOT * d)
#cant multiple an 18x18 by a 18x1 but i can a 2x2 by a 2x1

TypeError: Incompatible Qobj shapes