In [1]:
from qutip import *
import numpy as np
import matplotlib.pyplot as plt

#Sigma-X   sigmax()
#Sigma-Y   sigmay()
#Sigma-Z   sigmaz()
#Sigma plus   sigmap()
#Sigma minus   sigmam()
#identity   qeye(N)  (N=no. levels in hilbert space)

In [24]:
state1 = Qobj([[0,1],[1,0]])
print(state1)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[0. 1.]
 [1. 0.]]


In [25]:
z = sigmaz()
print(z)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = True
Qobj data =
[[ 1.  0.]
 [ 0. -1.]]


In [23]:
print(state1*z)

Quantum object: dims = [[2], [2]], shape = (2, 2), type = oper, isherm = False
Qobj data =
[[ 0. -1.]
 [ 1.  0.]]


In [32]:
fock_dm(5,4)

Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1.]]

In [33]:
print(0.5 * ket2dm(basis(5, 4)) + 0.5 * ket2dm(basis(5, 2)))
#same as print(0.5 * fock_dm(5, 4)) + 0.5 * fock_dm(5, 2)))


Quantum object: dims = [[5], [5]], shape = (5, 5), type = oper, isherm = True
Qobj data =
[[0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.5 0.  0. ]
 [0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.5]]
